require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/rails/migrations'
require 'capistrano/rails/assets'
require 'capistrano/webflow/base'
require 'capistrano/webflow/rails'
# require the mysql library if you use mysql
require 'capistrano/webflow/mysql'
# require the htaccess library for use the htaccess password protection
require 'capistrano/webflow/htaccess'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
